### ISSUE TITLE
Multiple chat channels in-game

### ISSUE THREAD

**Issue by Cuube** [Cuube/TeamGalaxy#5]
Galactica326 suggested to create a "staff chat" in-game. I like that idea.

**Comment by Schyrsivochter** [comment]
Couldn’t we use a pre-made plugin for this? There’s got to be one for that.

**Comment by Schyrsivochter** [comment]
Ah, forget about that. Let’s talk about details. What channels should we have? What should be special about those channels? A Staff channel would surely be only visible to staff, but other channels?

**Comment by Cuube** [comment]
> What channels should we have?
Well, I'm thinking about a staff member channel for every staff member and a channel for each group. (Builder, Dev, Admin, etc.)

> What should be special about those channels?
Hmm... well first off, only someone that has the permission (for example: teamgalaxy.channel.admin) can directly write into and receive messages from that channel. Why have I mentioned "directly"?

It's good that you asked what should be special about those channels because I have one more idea for the usage of channels. Players(Should be staff members) with the permission "teamgalaxy.channel" can write stuff into every channel, but that doesn't mean they can access them/receive messages. So these players are able to write something into the admin channel like: "cheater spotted on the smash server eu1: iTzInsertNamePvP2009". Also, when a /report command exists, which everybody should be able to use, reports will be sent to the admin channel.

**Comment by AxyyGX** [comment]
Maybe a chat for each group and a chat for all the staff

**Comment by Schyrsivochter** [comment]
That’s exactly what Cuube said
